services:
  selenium-hub:
    image: selenium/hub:latest
    platform: linux/amd64
    ports:
      - "4444:4444"
  chrome-node:
    image: selenium/node-chrome:latest
    platform: linux/amd64
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
    ports:
      - "5900"
  wiremock:
    image: wiremock/wiremock
    platform: linux/amd64
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files

  pytestifypro:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - wiremock
    environment:
      - DOCKER_ENV=true
    command: [ "sh", "-c", "poetry run pytest --alluredir=allure-results --log-cli-level=INFO -s" ]
