version: '3.8'
services:
  wiremock:
    image: wiremock/wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files

  pytestify:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - wiremock
    environment:
      - DOCKER_ENV=true
    command: [ "sh", "-c", "poetry run pytest --alluredir=allure-results --log-cli-level=INFO -s && allure serve allure-results" ]
