# src/pytestifypro/config/config.yaml
environments:
  sandbox:
    selenium:
      base_url: "https://title-chaining-sandbox.herokuapp.com"
      browser: "chrome"  # could be "firefox"
      headless: false
      #driver_path: "/path/to/chromedriver"
    
    database:
      host: "p.fy4z22xkwvekbm7ptaqepobuqy.db.postgresbridge.com"
      port: 5432
      user: "u_b2gqzeecvndepgjdifh6lnfkoe"
      password: "2ABW7aphfTmF2l6qrQD49yoSZoF8eROmAyUAi5rSYlBRJakwflfhpb7xsCWRph2E"
      database: "postgres"

    executor:
      name: "Local Execution"
      type: "Local"
      report_name: "Allure UI Automation Report"
      