# src/pytestifypro/config/config.yaml
environments:
  sandbox:
    selenium:
      base_url: "https://title-chaining-sandbox.herokuapp.com"
      browser: "chrome"  # could be "firefox"
      headless: false
      #driver_path: "/path/to/chromedriver"
    
    database:
      host: "localhost"
      port: 5433
      user: "postgres"
      password: "postgres"
      database: "title_chaining"
      